[phases.setup]
nixPkgs = [
    "nodejs",
    "python311",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.numpy",
    "python311Packages.opencv4",
    "python311Packages.pillow",
    "python311Packages.flask",
    "python311Packages.flask-cors",
    "python311Packages.requests",
    "python311Packages.gunicorn",
    "gcc",
    "stdenv.cc.cc.lib"
]

[phases.install]
cmds = [
    "cd backend && pip3 install --break-system-packages supabase",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "(cd backend && python3 -m gunicorn -b 0.0.0.0:5000 app_unified:app) & npm run preview"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"