[phases.setup]
nixPkgs = ["nodejs", "python3", "gcc"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash start.sh"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"