[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = [
    "cd backend && python -m pip install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash start.sh"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"