[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip", "python311Packages.setuptools", "gcc"]
aptPkgs = ["python3-pip"]

[phases.install]
cmds = [
    "cd backend && pip3 install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash start.sh"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"